default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: leora_juster_website_dev

test:
  <<: *default
  database: leora_juster_website_test

production:
  <<: *default
